### ISSUE TITLE
Property or indexer 'AbstractGuildedClient.Prepared' cannot be assigned to -- it is read only

### ISSUE THREAD

**Issue by djinnet** [Guilded-NET/Guilded.NET#2]
## Bug Description
Property or indexer 'AbstractGuildedClient.Prepared' cannot be assigned to -- it is read only.
Cannot assign an event to the prepared event.

## To reproduce
1: Create an console app with .Net 6
2: Add Guilded nuget to the project and copy & paste the documentation's example to the program.cs
3: Error shows in the Error List

## Expected behavior
The prepared isn't readonly, since we are required to assign an event to it. 

## Information
- **OS:** Windows 10
- **Version:** 0.7.4

## Additional Information
- Connected, disconnected and reconnected event also have the same issue as prepared. Common issue?

**Comment by IdkGoodName** [comment]
Hey there, thanks for submitting an issue.

If I am understanding this right, this is more so an issue with documentation being outdated. `.Prepared` used to be an event, but in 0.7.4+, it's now an observable.

If your code is:
```cs
client.Prepared += (o, e) => Console.WriteLine("I am prepared.");
```
Change it up to:
```cs
client.Prepared
      .Subscribe(me =>
          Console.WriteLine("I am prepared. Logged in as '{0}'", me.Name)
      );
```

Let me know if this helps.

**Comment by djinnet** [comment]
It works. I didn't see the example in the source code. Just the example in the documentation. 
Thanks for replied so quickly. 👍
