### ISSUE TITLE
Guilded.Templates failing

### ISSUE THREAD

**Issue by lyssieth** [Guilded-NET/Guilded.NET#8]
## Bug Description
After installing Guilded.Templates, whenever I try to use it (`dotnet new guilded.bot`), it prints the following error:
```
Unable to resolve the template, the following installed templates are conflicting:
[a table that doesn't paste well, see screenshot below]

The package Guilded.Templates is not correct, uninstall it and report the issue to the package author.
```

## To reproduce
1. Install `Guilded.Templates` using `dotnet new -i Guilded.Templates`
2. Try to create a new project using `dotnet new guilded.bot` (also works for `guilded.command`)

## Expected behavior
For it to create the project.

## Information
- **OS:** `Linux 6.0.1-arch2-1 x86_64`
- **Version:** Guilded.Templates::0.9.3 | dotnet 6.0.110

## Additional Information
![image](https://user-images.githubusercontent.com/1861988/196116890-1fd1aede-5195-498c-acca-01c529022a1b.png)

**Comment by IdkGoodName** [comment]
Thanks for reporting. Fixed in `Guilded.Templates` `1.0.0`
